### ISSUE TITLE
Implement NOVA vesting following locked FRAG

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#56] opened 2022-04-27 09:36 UTC
Users need to receive NOVA yield for their FRAG lock (on ETH)

**Comment by sinkingsugar** [comment] 2022-04-27 09:37
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/56?planning-poker) with ZenHub @guusw @Kryptos-FR @satendrapalsingh

**Comment by alebaffa** [comment] 2022-09-20 05:42
Closing as duplicate of #115 .

**Closed as completed** 2022-09-21 08:23 UTC
Labels: Type: New Feature, Status: Duplicate, pallet-accounts
